parameters:
  api.disablekey: true

env:
  contexts:
    - name: "Vulnerable API Demo"
      urls:
        - "http://temp-monitor-microservice-java:80"
      includePaths:
        - "http://temp-monitor-microservice-java:80/.*"

jobs:
  - type: openapi
    parameters:
      context: "Vulnerable API Demo"
      url: "http://temp-monitor-microservice-java:80/api-docs"

  - type: script
    parameters:
      action: add
      file: /zap/wrk/config/scripts/httpsender/intercept.js
      type: httpsender
      engine: Graal.js
      name: intercept.js

  - type: script
    parameters:
      action: add
      file: /zap/wrk/config/scripts/httpsender/log_requests.js
      type: httpsender
      engine: Graal.js
      name: log_requests.js

  - type: script
    parameters:
      action: add
      file: /zap/wrk/config/scripts/active/xss.js
      type: active
      engine: Graal.js
      name: xss.js

  - type: postman
    parameters:
      collectionFile: /zap/wrk/config/postman/postman-collection.json

  - type: delay
    parameters:
      time: 15

  - type: spider
    parameters:
      context: "Vulnerable API Demo"
      maxDuration: 60
      urls:
        - "http://temp-monitor-microservice-java:80/api"

  - type: passiveScan-config
    parameters:
      maxAlertsPerRule: 100
      maxBodySizeInBytesToScan: 2000000

  - type: activeScan
    parameters:
      context: "Vulnerable API Demo"
      policy: "Default Policy"

  - type: report
    parameters:
      template: "traditional-html"
      reportFile: "__REPORT_HTML__"

  - type: report
    parameters:
      template: "traditional-json"
      reportFile: "__REPORT_JSON__"