apiVersion: v1
kind: Service
metadata:
  name: temp-monitor-microservice-java
spec:
  selector:
    app: temp-monitor-microservice-java
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
      nodePort: 30181
  type: NodePort