apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards/my-dashboard.json
  - name: grafana-provisioning-dashboards
    files:
      - provisioning/dashboards/dashboards.yaml
  - name: grafana-provisioning-datasources
    files:
      - provisioning/datasources/datasources.yaml
  - name: grafana-provisioning-alert-rules
    files:
      - provisioning/alerting/temp-monitor-app-down.yaml

generatorOptions:
  disableNameSuffixHash: true