apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  labels:
    alertmanagerConfig: enabled
spec:
  route:
    receiver: 'email'
    repeatInterval: 30m
    routes:
      - matchers:
          - name: alertname
            value: HostHighCpuLoad
        repeatInterval: 2m
      - matchers:
          - name: alertname
            value: TempMonitorAppDown
        repeatInterval: 1m
  receivers:
    - name: 'email'
      emailConfigs:
        - to: 'stefangolubov84@gmail.com, stefan.golubov@avenga.com'
          from: 'stefangolubov84@gmail.com'
          smarthost: 'smtp.gmail.com:465'
          authUsername: 'stefangolubov84@gmail.com'
          authIdentity: 'stefangolubov84@gmail.com'
          authPassword:
            name: grafana-smtp
            key: smtp_password