apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - pvc.yaml
  - rbac.yaml
  - service.yaml
  - serviceaccount.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=config/prometheus.yml
  - name: prometheus-rules
    files:
      - alert-rules.yaml=config/alert-rules.yaml
