apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app/
  - monitoring/base/
  - security/zap/was/
  - security/zap/pentest/zap-pentest-job.yaml
  - newman/newman-collection-job.yaml