apiVersion: batch/v1
kind: Job
metadata:
  name: tmmj-zap-pentest-job
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: zap
          image: stefangolubov/zap-custom:latest
          securityContext:
            runAsUser: 1000
            runAsGroup: 1001
          env:
            - name: ZAP_LOG_LEVEL
              value: "DEBUG"
          command: ["sh", "-c"]
          args:
            - |
              mkdir -p /zap/wrk/zap && \
              timestamp=$(date +%Y%m%d-%H%M) && \
              html="/zap/wrk/zap/tmmj-pen-test-${timestamp}.html" && \
              json="/zap/wrk/zap/tmmj-pen-test-${timestamp}.json" && \
              sed "s|__REPORT_HTML__|$html|g; s|__REPORT_JSON__|$json|g" /zap/wrk/config/config/automation.yaml > /zap/wrk/automation-run.yaml && \
              zap.sh -cmd -autorun /zap/wrk/automation-run.yaml; \
              CODE=$?; \
              echo "ZAP exited with code $CODE"; \
              exit 0
          volumeMounts:
            - name: zap-config
              mountPath: /zap/wrk/config
              readOnly: true
            - name: zap-reports
              mountPath: /zap/wrk
      restartPolicy: Never
      volumes:
        - name: zap-config
          hostPath:
            path: "/mnt/d/DEV/ZAP"
            type: Directory
        - name: zap-reports
          persistentVolumeClaim:
            claimName: reports-pvc