groups:
  - name: main.rules
    rules:
      - alert: HostHighCpuLoad
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100 ) > 15
        for: 1m
        labels:
          severity: warning
        annotations:
          description: "CPU Load is over 50%\n Value = {{ $value }}\n Instance = {{ $labels.instance }} \n"
          summary: "Host CPU load high"
      - alert: TempMonitorAppDown
        expr: sum(kube_pod_container_status_running{container="temp-monitor-microservice-java", namespace="default"}) OR on() vector(0)
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Temp Monitor App Down"
          description: "No running containers found for deployment 'temp-monitor-microservice-java'."